[params]
  copyrightYears = "2013 - 2015"
  author = "Christian Mahnke"
  keywords = "Diaprojektor, Pr√§sentation, Upcycling"
  description = "Diaprojektor statt PowerPoint"
  enablePDFViewer = true

[params.author]
  email = 'mail@christianmahnke.de'
  name = 'Christian Mahnke'
  uri = 'http://www.wikidata.org/entity/Q137668638'
